server:
  port: 8086
spring:
  application:
    name: patient
  data:
    mongodb:
      authentication-database: admin
      username: user
      password: pass
      database: patient_db
      host: localhost
      port: 27017
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

springdoc:
  swagger-ui:
    path: apidoc

management:
  zipkin:
    tracing:
      enabled: true
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"