server:
  port: 8083
spring:
  application:
    name: physician
  data:
    mongodb:
      authentication-database: admin
      username: user
      password: pass
      database: physician_db
      host: localhost
      port: 27017
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
