server:
  port: 8082
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: physician
          uri: lb://PHYSICIAN
          predicates:
            - Path=/api/v1/physician/**
        - id: patient
          uri: lb://PATIENT
          predicates:
            - Path=/api/v1/patient/**
        - id: visit
          uri: lb://VISIT
          predicates:
            - Path=/api/v1/visit/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
